=== kvigor83/XML-Parser/data/toy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.third/kastsiuchenka.by/toys"
        xmlns:tns="http://www.third/kastsiuchenka.by/toys" elementFormDefault="qualified">
    <element name="toy" type="tns:Toy" abstract="true"></element>
    <element name="transport-toy" type="tns:Transport-toy" substitutionGroup="tns:toy"></element>
    <element name="music-toy" type="tns:Music-toy" substitutionGroup="tns:toy"></element>
    <element name="toys">
        <complexType>
            <sequence>
                <element ref="tns:toy" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Toy">
        <sequence>
            <element name="model" type="tns:Model"/>
            <element name="brand-name">
                <simpleType>
                    <restriction base="string">
                        <pattern value="(\w){3,20}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="material" type="tns:Material"/>
            <element name="cost" type="tns:Cost"/>
            <element name="external-parameters" type="tns:External-parameter"/>
        </sequence>
        <attribute name="toy-id" type="tns:Toy-id" use="required"/>
        <attribute name="toy-type" type="tns:Toy-type" use="required"/>
    </complexType>
    <complexType name="Transport-toy">
        <complexContent>
            <extension base="tns:Toy">
                <sequence>
                    <element name="type-transport" type="tns:Type-transport-toy"/>
                    <element name="type-control" type="tns:Type-control"/>
                    <element name="body-colour" type="tns:Colour"/>
                </sequence>
                <attribute name="number-weels" type="tns:Number-weels" use="required"/>
                <attribute name="scale" type="tns:Scale" use="optional" default="1:12"/>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Music-toy">
        <complexContent>
            <extension base="tns:Toy">
                <sequence>
                    <element name="type-music-toy" type="tns:Type-music-toy"/>
                    <element name="number-tones" type="tns:Number-tones"/>
                    <element name="main-colour" type="tns:Colour"/>
                </sequence>
                <attribute name="is-interactive" type="boolean" use="optional" default="false"/>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="Toy-id">
        <restriction base="ID">
            <pattern value="t\w{1,4}"/>
        </restriction>
    </simpleType>
    <simpleType name="Toy-type">
        <restriction base="string">
            <enumeration value="TRANSPORT_TOY"></enumeration>
            <enumeration value="SPORT_TOY"></enumeration>
            <enumeration value="DOLL"></enumeration>
            <enumeration value="MUSIC_TOY"></enumeration>
        </restriction>
    </simpleType>
    <simpleType name="Model">
        <restriction base="string">
            <pattern value="(\w){3,20}"/>
        </restriction>
    </simpleType>
    <simpleType name="Material">
        <restriction base="string">
            <enumeration value="PLASTIC"></enumeration>
            <enumeration value="WOOD"></enumeration>
            <enumeration value="STEEL"></enumeration>
            <enumeration value="GLASS"></enumeration>
            <enumeration value="TEXTALE"></enumeration>
            <enumeration value="PAPER"></enumeration>
        </restriction>
    </simpleType>
    <simpleType name="Cost">
        <restriction base="double">
            <pattern value="\d{1,4}[.]?\d{0,2}"/>
        </restriction>
    </simpleType>
    <complexType name="External-parameter">
        <sequence>
            <element name="weigth">
                <simpleType>
                    <restriction base="positiveInteger">
                        <minInclusive value="1"/>
                        <maxInclusive value="10000"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="length" type="tns:Size"/>
            <element name="width" type="tns:Size"/>
            <element name="heigth" type="tns:Size"/>
        </sequence>

    </complexType>
    <simpleType name="Size">
        <restriction base="integer">
            <minInclusive value="0"/>
            <maxInclusive value="200"/>
        </restriction>
    </simpleType>
    <simpleType name="Number-weels">
        <restriction base="positiveInteger">
            <minInclusive value="2"/>
            <maxInclusive value="10"/>
        </restriction>
    </simpleType>
    <simpleType name="Scale">
        <restriction base="string">
            <pattern value="([1][:]\d{1,2})?"/>
        </restriction>
    </simpleType>
    <simpleType name="Type-transport-toy">
        <restriction base="string">
            <enumeration value="TRUCK"></enumeration>
            <enumeration value="CAR"></enumeration>
            <enumeration value="TRAILER"></enumeration>
            <enumeration value="SPORTCAR"></enumeration>
            <enumeration value="BIKE"></enumeration>
            <enumeration value="EXCAVATOR"></enumeration>
        </restriction>
    </simpleType>
    <simpleType name="Type-music-toy">
        <restriction base="string">
            <enumeration value="PIANO"></enumeration>
            <enumeration value="PIPE"></enumeration>
            <enumeration value="DRUM"></enumeration>
            <enumeration value="GUITAR"></enumeration>
            <enumeration value="XYLOPHONE"></enumeration>
            <enumeration value="TAMBOURINE"></enumeration>
        </restriction>
    </simpleType>
    <simpleType name="Type-control">
        <restriction base="string">
            <enumeration value="MANUAL"></enumeration>
            <enumeration value="RADIO"></enumeration>
            <enumeration value="ELECTRICAL"></enumeration>
        </restriction>
    </simpleType>
    <simpleType name="Number-tones">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxInclusive value="40"/>
        </restriction>
    </simpleType>
    <simpleType name="Colour">
        <restriction base="string">
            <enumeration value="BLUE"></enumeration>
            <enumeration value="RED"></enumeration>
            <enumeration value="WHITE"></enumeration>
            <enumeration value="BLACK"></enumeration>
            <enumeration value="YELLOW"></enumeration>
            <enumeration value="ORANGE"></enumeration>
            <enumeration value="GREEN"></enumeration>
            <enumeration value="BROWN"></enumeration>
        </restriction>
    </simpleType>
</schema>

=== kvigor83/XML-Parser/data/toys.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<toys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:ns="http://www.third/kastsiuchenka.by/toys"
         xsi:schemaLocation="http://www.third/kastsiuchenka.by/toys toy.xsd">

    <music-toy toy-id="t1" toy-type="MUSIC_TOY" is-interactive="true">
        <model>FunnyPiano</model>
        <brand-name>CHUI</brand-name>
        <material>PLASTIC</material>
        <cost>120.00</cost>
        <external-parameters>
            <weigth>2000</weigth>
            <length>60</length>
            <width>30</width>
            <heigth>10</heigth>
        </external-parameters>
        <type-music-toy>PIANO</type-music-toy>
        <number-tones>40</number-tones>
        <main-colour>RED</main-colour>
    </music-toy>
    <music-toy toy-id="t2" toy-type="MUSIC_TOY" is-interactive="true">
        <model>dudka</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>7.50</cost>
        <external-parameters>
            <weigth>300</weigth>
            <length>20</length>
            <width>30</width>
            <heigth>20</heigth>
        </external-parameters>
        <type-music-toy>PIPE</type-music-toy>
        <number-tones>12</number-tones>
        <main-colour>YELLOW</main-colour>
    </music-toy>
    <transport-toy toy-id="t3" number-weels="4" scale="1:15"  toy-type="TRANSPORT_TOY">
        <model>molniya</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>250</weigth>
            <length>15</length>
            <width>15</width>
            <heigth>15</heigth>
        </external-parameters>
        <type-transport-toy>SPORTCAR</type-transport-toy>
        <type-control>MANUAL</type-control>
        <body-colour>RED</body-colour>
    </transport-toy>
    <music-toy toy-id="t4" toy-type="MUSIC_TOY" is-interactive="true">
        <model>baraban</model>
        <brand-name>mali</brand-name>
        <material>PLASTIC</material>
        <cost>7.50</cost>
        <external-parameters>
            <weigth>300</weigth>
            <length>20</length>
            <width>30</width>
            <heigth>20</heigth>
        </external-parameters>
        <type-music-toy>Drum</type-music-toy>
        <number-tones>12</number-tones>
        <main-colour>YELLOW</main-colour>
    </music-toy>
    <music-toy toy-id="t5" toy-type="MUSIC_TOY" is-interactive="true">
        <model>1234</model>
        <brand-name>malan</brand-name>
        <material>PLASTIC</material>
        <cost>100</cost>
        <external-parameters>
            <weigth>300</weigth>
            <length>20</length>
            <width>30</width>
            <heigth>20</heigth>
        </external-parameters>
        <type-music-toy>XYLOPHONE</type-music-toy>
        <number-tones>12</number-tones>
        <main-colour>YELLOW</main-colour>
    </music-toy>
    <transport-toy toy-id="t6" number-weels="4" scale="1:15"  toy-type="TRANSPORT_TOY">
        <model>pulya</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>250</weigth>
            <length>15</length>
            <width>15</width>
            <heigth>15</heigth>
        </external-parameters>
        <type-transport-toy>SPORTCAR</type-transport-toy>
        <type-control>MANUAL</type-control>
        <body-colour>RED</body-colour>
    </transport-toy>
    <transport-toy toy-id="t7" number-weels="4" scale="1:5"  toy-type="TRANSPORT_TOY">
        <model>shmulya</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>250</weigth>
            <length>15</length>
            <width>40</width>
            <heigth>15</heigth>
        </external-parameters>
        <type-transport-toy>TRUCK</type-transport-toy>
        <type-control>RADIO</type-control>
        <body-colour>RED</body-colour>
    </transport-toy>
    <transport-toy toy-id="t8" number-weels="4" scale="1:16"  toy-type="TRANSPORT_TOY">
        <model>molniya</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>250</weigth>
            <length>15</length>
            <width>15</width>
            <heigth>15</heigth>
        </external-parameters>
        <type-transport-toy>TRUCK</type-transport-toy>
        <type-control>MANUAL</type-control>
        <body-colour>RED</body-colour>
    </transport-toy>
    <transport-toy toy-id="t9" number-weels="4" scale="1:10"  toy-type="TRANSPORT_TOY">
        <model>pogruzchk</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>400</weigth>
            <length>15</length>
            <width>15</width>
            <heigth>15</heigth>
        </external-parameters>
        <type-transport-toy>TRUCK</type-transport-toy>
        <type-control>MANUAL</type-control>
        <body-colour>RED</body-colour>
    </transport-toy>
    <music-toy toy-id="t10" toy-type="MUSIC_TOY" is-interactive="false">
        <model>tramboline</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>20.00</cost>
        <external-parameters>
            <weigth>500</weigth>
            <length>20</length>
            <width>30</width>
            <heigth>20</heigth>
        </external-parameters>
        <type-music-toy>TAMBOURINE</type-music-toy>
        <number-tones>12</number-tones>
        <main-colour>BLUE</main-colour>
    </music-toy>
    <music-toy toy-id="t11" toy-type="MUSIC_TOY" is-interactive="false">
        <model>gitara</model>
        <brand-name>belvar</brand-name>
        <material>PLASTIC</material>
        <cost>17.50</cost>
        <external-parameters>
            <weigth>500</weigth>
            <length>20</length>
            <width>30</width>
            <heigth>20</heigth>
        </external-parameters>
        <type-music-toy>GUITAR</type-music-toy>
        <number-tones>12</number-tones>
        <main-colour>ORANGE</main-colour>
    </music-toy>
    <transport-toy toy-id="t12" number-weels="4" scale="1:11"  toy-type="TRANSPORT_TOY">
        <model>mumu</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>400</weigth>
            <length>15</length>
            <width>15</width>
            <heigth>15</heigth>
        </external-parameters>
        <type-transport-toy>EXCAVATOR</type-transport-toy>
        <type-control>MANUAL</type-control>
        <body-colour>RED</body-colour>
    </transport-toy>
    <transport-toy toy-id="t13" number-weels="4" scale="1:10"  toy-type="TRANSPORT_TOY">
        <model>pogruzchk2</model>
        <brand-name>polesie</brand-name>
        <material>PLASTIC</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>400</weigth>
            <length>15</length>
            <width>15</width>
            <heigth>45</heigth>
        </external-parameters>
        <type-transport-toy>TRUCK</type-transport-toy>
        <type-control>MANUAL</type-control>
        <body-colour>WHITE</body-colour>
    </transport-toy>
    <transport-toy toy-id="t14" number-weels="4" scale="1:12"  toy-type="TRANSPORT_TOY">
        <model>gruzovik</model>
        <brand-name>belvar</brand-name>
        <material>STEEL</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>500</weigth>
            <length>25</length>
            <width>15</width>
            <heigth>15</heigth>
        </external-parameters>
        <type-transport-toy>TRUCK</type-transport-toy>
        <type-control>MANUAL</type-control>
        <body-colour>RED</body-colour>
    </transport-toy>
    <transport-toy toy-id="t15" number-weels="4" scale="1:11"  toy-type="TRANSPORT_TOY">
        <model>pogruzchk</model>
        <brand-name>belaz</brand-name>
        <material>STEEL</material>
        <cost>12.00</cost>
        <external-parameters>
            <weigth>400</weigth>
            <length>34</length>
            <width>23</width>
            <heigth>20</heigth>
        </external-parameters>
        <type-transport-toy>EXCAVATOR</type-transport-toy>
        <type-control>MANUAL</type-control>
        <body-colour>BLACK</body-colour>
    </transport-toy>
    <music-toy toy-id="t16" toy-type="MUSIC_TOY" is-interactive="false">
        <model>funfun</model>
        <brand-name>belvar</brand-name>
        <material>PLASTIC</material>
        <cost>30.50</cost>
        <external-parameters>
            <weigth>500</weigth>
            <length>20</length>
            <width>30</width>
            <heigth>20</heigth>
        </external-parameters>
        <type-music-toy>XYLOPHONE</type-music-toy>
        <number-tones>12</number-tones>
        <main-colour>ORANGE</main-colour>
    </music-toy>
</toys>

=== kvigor83/XML-Parser/data/toys_unmarshaller.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns:toys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:ns="http://www.third/kastsiuchenka.by/toys"
         xsi:schemaLocation="http://www.third/kastsiuchenka.by/toys toy.xsd">

    <ns:music-toy toy-id="t1" toy-type="MUSIC_TOY" is-interactive="true">
        <ns:model>FunnyPiano</ns:model>
        <ns:brand-name>CHUI</ns:brand-name>
        <ns:material>PLASTIC</ns:material>
        <ns:cost>120.00</ns:cost>
        <ns:external-parameters>
            <ns:weigth>2000</ns:weigth>
            <ns:length>60</ns:length>
            <ns:width>30</ns:width>
            <ns:heigth>10</ns:heigth>
        </ns:external-parameters>
        <ns:type-music-toy>PIANO</ns:type-music-toy>
        <ns:number-tones>40</ns:number-tones>
        <ns:main-colour>RED</ns:main-colour>
    </ns:music-toy>
</ns:toys>
